Compile code

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,19 +1,41 @@
-name: Selenium Test WorkFlow
+name: Java run
 
 on: push
 
 jobs:
-  Selenium_Test_Job1:
-    name: Selenium Text Job
-    runs-on: windows-latest
+  build:
+    runs-on: ubuntu-latest
 
     steps:
-      - run: echo "This is running inside a ${{ runner.os }} server in GitHub"
-      - name: Check out source code
-        uses: actions/checkout@v2.4.0
-      - run: echo "This repo is ${{ github.repository }} .."
-      - name: Run a inline script
-        run: |
-          mkdir newfolder
-          ls -l
-        shell: bash
+    - name: checkout code
+      uses: actions/checkout@v2
+      
+    - name: Configurar JDK 11
+      uses: actions/setup-java@v2
+      with:
+        java-version: 11
+        distribution: 'temurin'
+        
+    - name: compile
+      run: |
+        javac -d . src/br/calebe/ticketmachine/**/*.java
+
+        if [ $? -ne 0 ]; then
+            echo "compile error"
+            exit 1
+        fi
+
+    - name: junit
+      run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
+
+    - name: execute junit
+      run: |
+        java -cp junit-platform-console-standalone-1.9.3.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
+        test_exit_code=$?
+
+        if [ $test_exit_code -eq 0 ]; then
+            echo "test sucess"
+        else
+            echo "test failed"
+            exit 1
+        fi
